sudo: required

language: cpp

services:
  - docker

script:
  - sudo docker build -f docker/ubuntu16.dockerfile -t vss-core-ubuntu16 .
  - sudo docker run vss-core-ubuntu16 test
  - sudo docker build -f docker/debian9.dockerfile -t vss-core-debian9.dockerfile .
  - sudo docker run vss-core-debian9.dockerfile test
  - sudo docker build -f docker/ubuntu18.dockerfile -t vss-core-ubuntu18 .
  - sudo docker run vss-core-ubuntu18 test

notifications:
  slack: vss-sdk:1bwlO40eKoIRA7l5yjLNqmjD