- name: Instalando pacotes
  apt: name={{ deb_padrao }} state=latest install_recommends=yes update_cache=yes

- name: Instalando pacotes adicionais para Debian 9
  apt: name={{ deb9 }} state=latest install_recommends=yes
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Instalando pacotes adicionais para Ubuntu 14
  apt: name={{ ubu14 }} state=latest install_recommends=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'

- name: Instalando pacotes adicionais para Ubuntu 16
  apt: name={{ ubu16 }} state=latest install_recommends=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'

- name: Instalando pacotes adicionais para Ubuntu 18
  apt: name={{ ubu18 }} state=latest install_recommends=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '18'

- name: Instalando pacotes adicionais para Mint 14
  apt: name={{ ubu14 }} state=latest install_recommends=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14'

# vim:ft=ansible :
